/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;


import Pack1.CourseDemo1;
import Pack1.ExamResult1;
import Pack1.FinalResult;
import Pack1.FinalResult1;
import Pack1.User;
import Pack1.UserRemote;
import java.awt.Color;
import java.awt.Image;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Pratik
 */
public class ClientMenu extends javax.swing.JFrame {

    /**
     * Creates new form ClientMenu
     */

    
   private Demo client=null;
    public ClientMenu()  {
        initComponents();
        //this.frm=frm;
       // ClientMenu c=new ClientMenu();
        //c.connect();
        
         String path="onlineexam.jpg";
      //  path="...\\Client\\loginform.png";
        ImageIcon img=new ImageIcon(path);
        
        jLabel2.setIcon(img);
         setState(JFrame.MAXIMIZED_BOTH);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }

    public ClientMenu(Demo A)
    {
         initComponents();
         try{
        //this.frm=frm;
       // ClientMenu c=new ClientMenu();
        //c.connect();
        client=A;
        
        User u= A.getUser();
        System.out.println("User Id is"+u.getUser());
        System.out.println("Password is"+u.getPass());
        
        String path="onlineexam.jpg";
      //  path="...\\Client\\loginform.png";
        ImageIcon img=new ImageIcon(path);
       // jLabel2.setIcon(img);
        Image im=img.getImage();
        if(im==null)
        {
            System.out.println("No Image");
        }
        else{
            System.out.println("Image is there"+im);
        }
        img=new ImageIcon(im);
        //jLabel1.setIcon(img);
        System.out.println("Image is there"+img);
        Image icon=new ImageIcon(this.getClass().getResource("removebg/online1.png")).getImage();
        setIconImage(icon);
        //jPanel1.setBackground(Color.red);
       // jLabel2.setIcon(img);
        setState(JFrame.MAXIMIZED_BOTH);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        System.out.println(""+getState());
         Image img1=new ImageIcon(this.getClass().getResource("removebg/student1.png")).getImage().getScaledInstance(50, 50, java.awt.Image.SCALE_SMOOTH);
           
         jMenuItem1.setIcon(new ImageIcon(img1));
         
          Image img2=new ImageIcon(this.getClass().getResource("removebg/logout1.png")).getImage().getScaledInstance(50, 50, java.awt.Image.SCALE_SMOOTH);
           
         jMenuItem6.setIcon(new ImageIcon(img2));
         
         Image img3=new ImageIcon(this.getClass().getResource("removebg/examnotify1.png")).getImage().getScaledInstance(50, 50, java.awt.Image.SCALE_SMOOTH);
           
         jMenuItem2.setIcon(new ImageIcon(img3));
         Image img4=new ImageIcon(this.getClass().getResource("removebg/notify1.png")).getImage().getScaledInstance(50, 50, java.awt.Image.SCALE_SMOOTH);
           
         jMenuItem4.setIcon(new ImageIcon(img4));
         
         Image img5=new ImageIcon(this.getClass().getResource("removebg/reportcard1.png")).getImage().getScaledInstance(50, 50, java.awt.Image.SCALE_SMOOTH);
           
         jMenuItem5.setIcon(new ImageIcon(img5));
         }catch(Exception ee)
         {
             System.out.println("Error in Client Menu "+ee);
            
                 }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/onlineexam.jpg"))); // NOI18N

        jMenu1.setText("Student");

        jMenuItem1.setText("Change Details");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem6.setText("LogOut");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Notifications");

        jMenuItem2.setText("FOR EXAM");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem4.setText("FOR RESULT");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Result");

        jMenuItem5.setText("GET REPORT");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 2019, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       // UserDetails frm=new UserDetails(client);
       try{
           
       System.out.println("Client is"+client);
     //  System.out.println("User is"+u);
      // StudentForm frm1=new StudentForm(client);
      StudentForm frm1=new StudentForm(client);
       frm1.setVisible(true);
       }
       catch(Exception ee)
       {
           System.out.println("Error in Menu"+ee);
       }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Notifications frm=new Notifications(client);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
         ExamResult frm=new ExamResult(client);
         frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
//       ReportCard rep=new ReportCard(client);
//                       rep.setVisible(true);
        
        
        User u=client.getUser();
       //UserRemote user=Demo.
       int sid=u.getId();
       int course=u.getCourse();
       UserRemote ur=Demo.getUserRemote();
       try {
           List<CourseDemo1> list1=ur.courseDetails(course);
           Iterator it=list1.iterator();
           if(it.hasNext())
           {
//               CourseDemo1 crs=new CourseDemo1();
               CourseDemo1 crs=(CourseDemo1)it.next();
               String cname=crs.getCname();
               if(cname!=null)
               {
                  //String query="select * from studentresult where sid="+sid+" and cname='"+cname+"'"; 
                   //List<ExamResult1> list2=ur.getStudentResult1(query);
                   System.out.println("Hello"+sid+cname);
                   List<FinalResult> list2=ur.getFinalReport(sid,cname);
                   
                   System.out.println("Hello1");
                   Iterator it1=list2.iterator();
                   if(it1.hasNext())
                   {   
                       System.out.println("Client is"+client);
                       ReportCard1 rep=new ReportCard1(client);
                       rep.setVisible(true);
                   }
                   else{
                       JOptionPane.showMessageDialog(this,"No Result is There");
                   }   
                   
               }
               else{
                   JOptionPane.showMessageDialog(this,"Course is not There");
               }
           }
           
       } catch (Exception ee) {
          System.out.println("GET REPORT ERROR"+ee);
       }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        this.dispose();
        LoginForm log=new LoginForm();
        log.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    // End of variables declaration//GEN-END:variables
}
