/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import Pack1.CourseDemo1;
import Pack1.ExamResult1;
import Pack1.SubjectDemo1;
import Pack1.User;
import Pack1.UserRemote;
import java.awt.Color;
import java.awt.Container;
import java.awt.Image;
import java.util.Iterator;
import java.util.List;
import java.util.function.Consumer;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pratik
 */
public class ExamResult extends javax.swing.JFrame {

    /**
     * Creates new form ExamResult1
     */
    public ExamResult() {
        initComponents();
        Container ctx=getContentPane();
            ctx.setBackground(new Color(255,255,150));
            setTitle("Exam Results");
Image icon=new ImageIcon(this.getClass().getResource("removebg/online1.png")).getImage();
setIconImage(icon);
    }
    public List<ExamResult1> list=null,list3=null;
    public List<SubjectDemo1> list1=null;
    public List<CourseDemo1> list2=null;
    String query="";
    public ExamResult(Demo inform) {
        initComponents();
        try{
            Container ctx=getContentPane();
            ctx.setBackground(new Color(255,255,150));
            User u=inform.getUser();
            int sid=u.getId();
            UserRemote ur=Demo.getUserRemote();
            query="select * from studentresult where sid="+sid;
            int cid=u.getCourse();
            list2=ur.courseDetails(cid);
//            Iterator it2=list2.iterator();
//            while(it2.hasNext())
//            {
//                CourseDemo1 crs=(CourseDemo1)it2.next();
//                jTextField1.setText(crs.getCname());
//            }
            list2.forEach(new ConsumerImpl());
            String cname=jTextField1.getText();
            
            
            list1=ur.subjectDetails(cname);
            Iterator it1=list1.iterator();
            while(it1.hasNext())
            {
               SubjectDemo1 sub=(SubjectDemo1)it1.next();
               jComboBox1.addItem(sub.getSname());
               
            }
            
            list=ur.getStudentResult(sid);
            
            Iterator it=list.iterator();
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            while(it.hasNext())
            {
                ExamResult1 res=(ExamResult1)it.next();
                if(res.getResstate().equalsIgnoreCase("Declared"))
                model.addRow(new Object[]{res.getSid(),res.getEid(),res.getStuname(),res.getCname(),res.getSname(),res.getTotalq(),res.getAttques(),res.getObtmarks(),res.getResult(),res.getResstate()});
            }
            
            
            
        }catch(Exception ee)
        {
            System.out.println("Exception ee"+ee);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Course Name");

        jLabel2.setText("Subject Name");

        jButton1.setText("Get Results");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Exam ID", "Student Name", "Course Name", "Subject Name", "Total Questions", "Attempted Questions", "Obtained Marks", "Result", "ResultState"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1039, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(184, 184, 184)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(130, 130, 130)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(1, 1, 1)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try{
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            int rowidx=jTable1.getSelectedRow();
            int eid=Integer.parseInt(model.getValueAt(rowidx, 0).toString());
//            DeclareExams frm=new DeclareExams(eid);
//            frm.setVisible(true);

        }catch(Exception ee)
        {
            System.out.println("Get Attempted Exam Table Error"+ee);
        }
    }//GEN-LAST:event_jTable1MouseClicked
String query1="";
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          try{
              DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
              while(model.getRowCount()>0)
              { 
                  model.removeRow(model.getRowCount()-1);
              }
              String sname1=jComboBox1.getSelectedItem().toString();
              query1=query+" and sname='"+sname1+"'";
              System.out.println("Query is "+query1);
              UserRemote ur=Demo.getUserRemote();
              list3=ur.getStudentResult1(query1);
            Iterator it3=list3.iterator();
            while(it3.hasNext())
            {
               ExamResult1 res=(ExamResult1)it3.next();
               if(res.getResstate().equalsIgnoreCase("Declared"))
                model.addRow(new Object[]{res.getSid(),res.getEid(),res.getStuname(),res.getCname(),res.getSname(),res.getTotalq(),res.getAttques(),res.getObtmarks(),res.getResult(),res.getResstate()});
                
//               jComboBox1.addItem(sub.getSname());
               
            }
              query1=query;
    
          }catch(Exception ee)
          {
              System.out.println("Button Exception "+ee);
          }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExamResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private class ConsumerImpl implements Consumer<CourseDemo1> {

        public ConsumerImpl() {
        }

        @Override
        public void accept(CourseDemo1 crs) {
            jTextField1.setText(crs.getCname());
        }
    }
}
